### ISSUE TITLE
Is it possible to take a screenshot of website that makes a redirection?

### ISSUE THREAD

**Issue by TahaBoulehmi** [legraphista/node-server-screenshot#16]
I would like to make a screenshot of 'bluecrate.com', so I tried to run this:

```javascript
var app = require("node-server-screenshot");
app.fromURL("https://bluecrate.com", "test.png",{waitMilliseconds: 5000}, function(err){
  console.log(err);
});
```

The problem is that the website makes a redirection to 'uk.bluecrate.com' before that the module takes the screenshot.

```bash
{ Error: navigation error
    at unserializeError (/Users/taha/Documents/development/project/node_modules/nightmare/lib/ipc.js:162:13)
    at EventEmitter.<anonymous> (/Users/taha/Documents/development/project/node_modules/nightmare/lib/ipc.js:89:13)
    at Object.onceWrapper (events.js:285:13)
    at EventEmitter.emit (events.js:197:13)
    at ChildProcess.<anonymous> (/Users/taha/Documents/development/project/node_modules/nightmare/lib/ipc.js:49:10)
    at ChildProcess.emit (events.js:197:13)
    at emit (internal/child_process.js:834:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17) code: -3, url: 'https://bluecrate.com/' }
```

**Is there any way to stop the page from making the redirection until the module takes the screenshot? Or at least to take the screenshot after the redirection?**

I'm using a Macbook Pro.

**Comment by TahaBoulehmi** [comment]
I fixed the issue and made a pull request :)

**Comment by legraphista** [comment]
Thanks for the PR! Much appreciated!
