### ISSUE TITLE
.finally is not a function

### ISSUE THREAD

**Issue by didintri196** [legraphista/node-server-screenshot#21]
/home/multectc/development/node/scrapper/node_modules/node-server-screenshot/index.js:104
  .finally(function() {
          ^

TypeError: n.viewport(...).goto(...).wait(...).wait(...).screenshot(...).then(...).catch(...).finally is not a function
    at Object.module.exports.fromURL (/home/multectc/development/node/scrapper/node_modules/node-server-screenshot/index.js:104:11)
    at Object.<anonymous> (/home/multectc/development/node/scrapper/index.js:2:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by legraphista** [comment]
Hi @didintri196 
Thank you for your report!
Unfortunately I cannot reproduce your crash

Can you please provide more details like node's version and/or if you use a custom 3rd party promise library?

**Comment by adamcsk1** [comment]
> /home/multectc/development/node/scrapper/node_modules/node-server-screenshot/index.js:104
> .finally(function() {
> ^
> 
> TypeError: n.viewport(...).goto(...).wait(...).wait(...).screenshot(...).then(...).catch(...).finally is not a function
> at Object.module.exports.fromURL (/home/multectc/development/node/scrapper/node_modules/node-server-screenshot/index.js:104:11)
> at Object. (/home/multectc/development/node/scrapper/index.js:2:5)
> at Module._compile (module.js:652:30)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)
> at Function.Module.runMain (module.js:693:10)
> at startup (bootstrap_node.js:188:16)
> at bootstrap_node.js:609:3

Just you have to update your nodejs to latest version and after will work.

**Comment by didintri196** [comment]
my version node v12.13.1
